apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: tolebi1/accounts:latest
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:Zxcvbnm123@postgres:5432/exp5?sslmode=disable"
